# Colors (One Dark)

# Default colors
[colors.primary]
background = '#232326'
foreground = '#a7aab0'

# Normal colors
[colors.normal]
black   = '#101012'
red     = '#de5d68'
green   = '#8fb573'
yellow  = '#dbb671'
blue    = '#57a5e5'
magenta = '#bb70d2'
cyan    = '#51a8b3'
white   = '#a7aab0'
