[colors.bright]
black = "#545454"
blue = "#569cd6"
cyan = "#56b6c2"
green = "#608b4e"
magenta = "#c678dd"
red = "#f44747"
white = "#d4d4d4"
yellow = "#dcdcaa"

[colors.cursor]
cursor = "#d4d4d4"
text = "#d4d4d4"

[colors.normal]
black = "#1e1e1e"
blue = "#569cd6"
cyan = "#56b6c2"
green = "#608b4e"
magenta = "#c678dd"
red = "#f44747"
white = "#d4d4d4"
yellow = "#dcdcaa"

[colors.primary]
background = "#1e1e1e"
foreground = "#d4d4d4"

[env]
TERM = "xterm-256color"

[font]
size = 28

[font.normal]
family = "Agave Nerd Font Mono"
style = "Regular"
[keyboard]
bindings = [
  {key="T", mods="Command", action="CreateNewTab"},
  {key="Tab", mods="Control", action="SelectNextTab"},
  {key="Tab", mods="Control|Shift", action="SelectPreviousTab"},
  {key="b", mods="Control", action="ScrollPageUp", mode="vi"},
  {key="f", mods="Control", action="ScrollPageDown", mode="vi"},
  {key="d", mods="Control", action="ScrollHalfPageUp", mode="vi"},
  {key="u", mods="Control", action="ScrollHalfPageDown", mode="vi"},
  {key="o", mods="Command", action="Open", mode="vi"},
  {key="s", mods="Command", action="ToggleViMode"},
  {key="c", mods="Control", action="ToggleViMode", mode="vi"},
  {key="/", action="SearchBackward", mode="vi"},
  {key="g", mods="Command", action="SearchFocusPrevious", mode="vi"},
  {key="g", mods="Command|Shift", action="SearchFocusNext", mode="vi"},
]

[window]
dynamic_padding = true
opacity = 1
option_as_alt = "Both"

